services:
  ocoffee_test-app:
    container_name: ocoffee_test-app
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - ./.env.test
    environment:
      - NODE_ENV=test
    ports:
      - "${PORT}:3000"
    volumes:
      - ./app:/usr/src/app
  ocoffee_test-db:
    container_name: ocoffee_test-db
    image: postgres:latest
    env_file:
      - ./.env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ocoffee_test_data:/var/lib/postgresql/data
volumes:
  ocoffee_test_data: