-- Generated by Mocodo 4.2.11

CREATE TABLE COFFEE (
  PRIMARY KEY (name),
  name        VARCHAR(42) NOT NULL,
  reference   VARCHAR(42),
  description VARCHAR(42),
  price       VARCHAR(42),
  available   VARCHAR(42),
  name_2      VARCHAR(42) NOT NULL,
  name_3      VARCHAR(42) NOT NULL
);
