name: 🚀 Deploy OCoffee gh-pages

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔬 Lancement des tests
        run: npm run test || echo "⚡ No tests found, skipping..."
      
      - name: 🚀 Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./